### ISSUE TITLE
Contributors documentation

### ISSUE THREAD

**Issue by ShutdownRepo** [ThePorgs/Exegol-docs#1]
Have the code documented dynamically through its comments and structure, and document how contributors can help out

**Comment by noraj** [comment]
Suggestions:

- Target the `dev` branch
- Try to submit only one tool per PR

**Comment by ShutdownRepo** [comment]
https://exegol.readthedocs.io/en/latest/community/contributors.html ✅
Thank you for the suggestions
Will improve this side of the documentation in the future, it's really basic right now (happy to review PRs on the docs repo 😉 )

**Comment by ShutdownRepo** [comment]
Started with https://github.com/ThePorgs/Exegol-docs/commit/fef12043b18913b5e5c1ab6cdb95a9a967d9def6
@noraj I'd be happy to have your feedback on that (will be [built here](https://exegol.readthedocs.io/en/dev-images/community/contributors.html) in a few minutes)

**Comment by noraj** [comment]
The doc seems detailed enough. Well done

**Comment by ShutdownRepo** [comment]
Closing here, coming with #31 
While the contributors doc currently focuses on the images, it's where most external contributions come from, so it makes sense. Wrapper doc will come later on.
