### ISSUE TITLE
Add warning about Python installation on Windows

### ISSUE THREAD

**Issue by sebdufourcq** [ThePorgs/Exegol-docs#23]
## Description
Following the documentation, `python3` command is not working on Windows and prevents the installation of Exegol.

The Windows Python full installer only allows the following commands:
- `py` : the Python Launcher will start the latest version of Python installed
- `python`: only available if the following option is checked during install  `Add python.exe to PATH`

The Microsoft Store package must be installed in order to make the `python3` command available.

## Action
- [ ] Add a warning in the documentation for Windows users
- [ ] Update the link to the latest Python Microsoft Store package https://apps.microsoft.com/store/detail/python-311/9NRWMJP3717K

**Comment by Malsius** [comment]
There is a tip in the documentation to avoid this behaviour:
```
If you have installed Python3 manually and Windows opens the Microsoft store on the python page as soon as you type python3.exe, try this:

It is possible to disable this behavior in the Windows settings: Apps > Apps & features > App execution aliases and disable aliases for python.exe and python3.exe.
```

**Comment by ShutdownRepo** [comment]
@Dramelac any insight on this?

**Comment by Dramelac** [comment]
What is your error exactly @sebdufourcq ?
I understand you want to redirect user to the microsoft store instead of the officiel python installer but why ?

**Comment by sebdufourcq** [comment]
`python3` is an alias only created by default on Linux-based OS and macOS. (`py`  is recommended for Windows)

With the Windows Installer, there is no python3.exe, so following the step [1. Installation of exegol](https://exegol.readthedocs.io/en/latest/getting-started/install.html#id6) (with pip or pipx) will result in an error.
`The term 'python3' is not recognized as the name of a cmdlet, function, script file, or operable program.`

One workaround is to copy the "python.exe" and rename it to "python3.exe"
An other way is to install it from the windows store and make sure python3.exe alias is enabled.
Or warn that you have to replace all `python3` commands with `py`...

Or follow the first doc hint :-)
> It is strongly advised to install Exegol on a Linux host

**Comment by Dramelac** [comment]
A tip has been added : https://exegol.readthedocs.io/en/latest/getting-started/install.html#adding-exegol-to-the-path
Closing now
